name: deleted-later
on: [push]

jobs:
  windows-why:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [Win32, x64, ARM64]
    steps:
    - name: Print Environment Variables
      shell: cmd
      run: set
    - name: Print CMake Version
      shell: cmd
      run: cmake --version
    - name: Checkout Current Repository
      uses: actions/checkout@v2
      with:
        path: repo
    - name: Dump all CMake variables starting with CMAKE_VS_
      shell: cmd
      run: cmake -B__dummy__ -Hrepo/cmakevardump
    - name: Checkout OpenAL-soft
      uses: actions/checkout@v2
      with:
        path: openal-soft
        repository: kcat/openal-soft
    - name: Configure
      shell: cmd
      env:
        WINARCH: ${{ matrix.platform }}
      run: cmake -Bbuild -Hopenal-soft -DCMAKE_INSTALL_PREFIX=%CD%\install -A %WINARCH%
    - name: Build & Install
      shell: cmd
      run: cmake --build build --config Release --target install
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: openal-soft-${{ matrix.platform }}
        path: install
