name: deleted-later
on: [push]

jobs:
  windows-why:
    runs-on: windows-latest
    continue-on-error: ${{ matrix.release == 'master' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
        release: [master, '873983377052594b418bfa6cd505df7c604792ea', 'f49238c79278bb019e618b23d9b86d2ba15f82c2', 'be476c793574fcde7bb78df1595257cc52f4c93a']
    steps:
    - name: Print Environment Variables
      shell: cmd
      run: set
    - name: Print CMake Version
      shell: cmd
      run: cmake --version
    - name: Checkout Current Repository
      uses: actions/checkout@v2
      with:
        path: repo
    - name: Dump all CMake variables starting with CMAKE_VS_
      shell: cmd
      run: cmake -B__dummy__ -Hrepo/cmakevardump
    - name: Checkout OpenAL-soft
      uses: actions/checkout@v2
      with:
        path: openal-soft
        repository: kcat/openal-soft
        ref: ${{ matrix.release }}
    - name: Configure
      shell: cmd
      env:
        WINARCH: ${{ matrix.platform }}
      run: cmake -Bbuild -Hopenal-soft -DCMAKE_INSTALL_PREFIX=%CD%\install -A %WINARCH%
    - name: Build & Install
      shell: cmd
      run: cmake --build build --config Release --target install
